[package]
name = "cho-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
cho-lib = { path = "../cho-lib" }
clap = { version = "4.5.20", features = ["derive"] }
ron = "0.8.1"
serde = { version = "1.0.214", features = ["derive"] }
