on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: zip addon
        run: | # this zips the addons folder into an archive we can release
          zip -r -y choreograper.zip . -i ./addons
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            LICENSE.txt
            choreographer.zip
      - name: cleanup
        run:
          rm choreographer.zip
